export const brandColors = {
  primary: "#0f766e",
  primaryHover: "#0b5f59",
  primaryActive: "#094b46",
  accent: "#d97706",
  background: "#f4f7f6",
  backgroundSoft: "#edf5f3",
  surface: "#ffffff",
  surfaceStrong: "#f8fbfa",
  border: "#d7e3df",
  text: "#1f2937",
  textMuted: "#667085",
  tag: "#fdf2e8",
  tagText: "#b45309",
  success: "#15803d",
  warning: "#b45309",
  danger: "#b42318",
  glow: "0 16px 40px rgba(15, 23, 42, 0.06)",
  radius: 14,
};

export const appFontFamily = '"Satoshi-Medium", "Satoshi-Light", "Helvetica Neue", sans-serif';

export const antdYellowTheme = {
  token: {
    colorPrimary: brandColors.primary,
    colorInfo: brandColors.primary,
    colorSuccess: brandColors.success,
    colorWarning: brandColors.warning,
    colorError: brandColors.danger,
    colorBgBase: brandColors.background,
    colorBgContainer: brandColors.surface,
    colorBorder: brandColors.border,
    colorTextBase: brandColors.text,
    colorText: brandColors.text,
    colorTextSecondary: brandColors.textMuted,
    colorTextPlaceholder: "#98a2b3",
    colorLink: brandColors.primary,
    colorLinkHover: brandColors.primaryHover,
    colorLinkActive: brandColors.primaryActive,
    borderRadius: brandColors.radius,
    fontFamily: appFontFamily,
    boxShadow: brandColors.glow,
  },
  components: {
    Layout: {
      bodyBg: brandColors.background,
      headerBg: brandColors.surface,
      footerBg: brandColors.background,
      siderBg: brandColors.surface,
      triggerBg: brandColors.primary,
    },
    Button: {
      primaryShadow: "none",
      defaultBorderColor: brandColors.border,
      defaultHoverBorderColor: brandColors.primary,
      defaultHoverColor: brandColors.primary,
      borderRadius: 12,
      contentFontSize: 14,
      controlHeight: 40,
    },
    Input: {
      activeBorderColor: brandColors.primary,
      hoverBorderColor: brandColors.primaryHover,
      borderRadius: 12,
      controlHeight: 44,
    },
    DatePicker: {
      activeBorderColor: brandColors.primary,
      hoverBorderColor: brandColors.primaryHover,
      borderRadius: 12,
      controlHeight: 44,
    },
    Form: {
      labelColor: brandColors.text,
    },
    Menu: {
      itemSelectedColor: brandColors.primary,
      itemSelectedBg: brandColors.backgroundSoft,
      itemHoverColor: brandColors.primaryHover,
      horizontalItemSelectedColor: brandColors.primary,
    },
    Table: {
      headerBg: brandColors.surfaceStrong,
      rowHoverBg: brandColors.backgroundSoft,
      borderColor: brandColors.border,
      headerColor: brandColors.text,
    },
    Alert: {
      colorWarningBg: "#fff7ed",
      colorWarningBorder: "#fed7aa",
    },
    Tag: {
      defaultBg: brandColors.tag,
      defaultColor: brandColors.tagText,
    },
    Tabs: {
      itemColor: brandColors.textMuted,
      itemSelectedColor: brandColors.text,
      itemHoverColor: brandColors.primary,
      inkBarColor: brandColors.primary,
      horizontalMargin: "0 0 20px 0",
    },
    Card: {
      borderRadiusLG: 18,
    },
  },
};
